#!/bin/sh
set -eu

cd "$(dirname "$0")/../.."
set -x

cargo --version
cargo fmt --all --check
cargo clippy --workspace --all-targets --locked -- -D warnings
cargo build --workspace --locked
cargo test --workspace --locked
