use std::fmt;

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use zeroize::Zeroize;

use crate::id::uuid_v7_id;

uuid_v7_id! {
    /// A key account's id: a version 7 UUID that the client generates once and sends again on
    /// every retry of `accounts/keys/add`.
    AccountId
}

/// Who a stored API key is for (0004's fallback for a subscription).
///
/// A newer wispd may send providers that are not listed here. Treat those as unknown, so a
/// `switch` over this type must not end in an exhaustiveness assertion.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum Provider {
    /// Anthropic, Claude Max's fallback.
    Anthropic,
    /// `OpenAI`, `ChatGPT` Plus's fallback.
    Openai,
    /// Cursor, Cursor Pro+'s fallback.
    Cursor,
    /// A provider this version does not know yet.
    #[serde(other)]
    #[ts(skip)]
    Unknown,
}

/// An API key on the wire.
///
/// It serializes and deserializes as a plain string (serde's newtype-struct representation is
/// already transparent in JSON, so `#[serde(transparent)]` would be redundant here, and ts-rs 12
/// cannot parse it), but its `Debug` never shows the value, so a stray `{:?}` in a log line can't
/// leak it (#117). Compare wispd's `backend::ApiKey`, which does the same for the key once it
/// reaches a backend.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct RawKey(String);

impl RawKey {
    /// The key itself, for the one place that stores it: wispd's `KeyStore`.
    #[must_use]
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for RawKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RawKey(<redacted>)")
    }
}

impl Drop for RawKey {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// A key account: its record in wisp's store. The key itself lives only in the macOS Keychain
/// (0004); wispd never returns it unmasked.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct KeyAccount {
    /// The id the client chose when it added the key.
    pub id: AccountId,
    /// Who the key is for.
    pub provider: Provider,
    /// A label the user chose, shown in the editor.
    pub label: String,
    /// When the key was added, in RFC 3339 UTC.
    pub created_at: Timestamp,
    /// The key, masked: its vendor prefix and last 4 characters, such as `sk-ant-...abcd`.
    pub masked_key: String,
}

/// Params of `accounts/keys/add`.
///
/// It is idempotent on `id`: adding the same id again with the same `provider`, `label`, and
/// `key` returns the existing account instead of storing the key twice, and fails with
/// `idConflict` if they differ. The key is sent once; wispd stores it in the Keychain and never
/// echoes it back unmasked.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysAddParams {
    /// The new account's id, a version 7 UUID generated by the client.
    pub id: AccountId,
    /// Who the key is for.
    pub provider: Provider,
    /// A label the user chose, shown in the editor.
    pub label: String,
    /// The key. Never logged, never written anywhere but the Keychain, and never sent back.
    pub key: RawKey,
}

/// Result of `accounts/keys/add`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysAddResult {
    /// The account, with its key masked.
    pub account: KeyAccount,
}

/// Params of `accounts/keys/list`.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysListParams {}

/// Result of `accounts/keys/list`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysListResult {
    /// Every key account, oldest first, with its key masked.
    pub accounts: Vec<KeyAccount>,
}

/// Params of `accounts/keys/remove`.
///
/// Removing an id that does not exist fails with `accountNotFound`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysRemoveParams {
    /// The account to remove.
    pub id: AccountId,
}

/// Result of `accounts/keys/remove`.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AccountsKeysRemoveResult {}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::RawKey;

    #[test]
    fn a_raw_key_never_shows_its_value_in_debug() {
        let key: RawKey = serde_json::from_value(json!("sk-ant-super-secret")).unwrap();
        assert_eq!(key.expose(), "sk-ant-super-secret");
        assert_eq!(format!("{key:?}"), "RawKey(<redacted>)");
    }
}
