//! `context/list`, `context/read`, and `context/write` (0005, #155): the shared context folder
//! wispd keeps for each project, outside its git repository, that every agent and the editor read
//! and write.
//!
//! A path is always relative to the project's context folder, and is exactly one file name: no
//! `..`, no leading `/`, no hidden (dot) name, and no subdirectories. wispd only ever holds
//! Markdown or plain text there, so a path must end in `.md`, `.markdown`, or `.txt`.

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::ProjectId;
use crate::id::uuid_v7_id;

uuid_v7_id! {
    /// A `context/write`'s id: a version 7 UUID that the client generates once and sends again on
    /// every retry, so a retry never applies the write twice or emits a duplicate `context.changed`
    /// event.
    ContextWriteId
}

/// One shared context file, without its content.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextFile {
    /// The file's name, relative to the project's context folder.
    pub path: String,
    /// Its size in bytes.
    pub size: u64,
    /// When it was last modified, in RFC 3339 UTC.
    pub modified_at: Timestamp,
    /// Who wrote it last, such as `"editor"` or an agent's run id, when wispd knows. Absent for a
    /// file wispd has not seen written since it started, such as one already on disk at startup.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub last_writer: Option<String>,
}

/// Params of `context/list`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextListParams {
    /// The project whose shared context to list.
    pub project: ProjectId,
}

/// Result of `context/list`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextListResult {
    /// Every file in the project's shared context, ordered by path.
    pub files: Vec<ContextFile>,
}

/// Params of `context/read`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextReadParams {
    /// The file's project.
    pub project: ProjectId,
    /// The file's path. Fails with `contextNotFound` if it does not exist.
    pub path: String,
}

/// Result of `context/read`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextReadResult {
    /// The file's metadata.
    pub file: ContextFile,
    /// Its content.
    pub content: String,
}

/// Params of `context/write`.
///
/// It is idempotent on `id`: writing the same id again with the same `project`, `path`,
/// `content`, and `writer` returns the same result instead of writing twice or emitting a second
/// `context.changed` event; with different params it fails with `idConflict`. A write to a path
/// with existing content replaces it; the last write to a path wins when two race (0005).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextWriteParams {
    /// The write's id, a version 7 UUID generated by the client.
    pub id: ContextWriteId,
    /// The file's project.
    pub project: ProjectId,
    /// The file's path.
    pub path: String,
    /// The file's new content, in full: `context/write` replaces a file, it does not patch one.
    pub content: String,
    /// A label for who is writing, such as `"editor"` or an agent's run id, shown later in
    /// `context/list` and in the `context.changed` event as `lastWriter`. Omitted when the caller
    /// has none to give.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub writer: Option<String>,
}

/// Result of `context/write`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ContextWriteResult {
    /// The written file's metadata.
    pub file: ContextFile,
}
