use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::id::uuid_v7_id;

uuid_v7_id! {
    /// A project's id: a version 7 UUID that the client generates once and sends again on every
    /// retry of `project/create`.
    ProjectId
}

/// A project: a body of work on one repository, run by this wispd.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    /// The id the client chose when it created the project.
    pub id: ProjectId,
    /// The name shown in the editor.
    pub name: String,
    /// The absolute path of the repository on this host.
    pub repo_path: String,
    /// When the project was created, in RFC 3339 UTC.
    pub created_at: Timestamp,
    /// When the project last changed, in RFC 3339 UTC.
    pub updated_at: Timestamp,
}

/// Params of `project/list`.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ProjectListParams {}

/// Result of `project/list`: a snapshot of every project.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ProjectListResult {
    /// Every project, oldest first.
    pub projects: Vec<Project>,
    /// The `seq` of the last event the snapshot reflects. Subscribe with `after` set to it.
    pub seq: u64,
}

/// Params of `project/create`.
///
/// It is idempotent on `id`: if a project with that id exists, wispd returns it instead of
/// creating another, and fails with `idConflict` if `name` or `repoPath` differ.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ProjectCreateParams {
    /// The new project's id, a version 7 UUID generated by the client.
    pub id: ProjectId,
    /// The name shown in the editor.
    pub name: String,
    /// The absolute path of the repository on this host.
    pub repo_path: String,
}

/// Result of `project/create`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ProjectCreateResult {
    /// The project, new or existing.
    pub project: Project,
}
